# Generated by Django 4.1.5 on 2023-02-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_feedback_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_no', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('q1', models.CharField(max_length=50)),
                ('q2', models.CharField(max_length=50)),
                ('q3', models.CharField(max_length=50)),
                ('q4', models.CharField(max_length=50)),
                ('q5', models.CharField(max_length=50)),
                ('q6', models.CharField(max_length=50)),
                ('q7', models.CharField(max_length=50)),
                ('q8', models.CharField(max_length=50)),
                ('q9', models.CharField(max_length=50)),
                ('q10', models.CharField(max_length=50)),
                ('q11', models.CharField(max_length=50)),
                ('q12', models.CharField(max_length=50)),
                ('q13', models.CharField(max_length=50)),
                ('q14', models.CharField(max_length=50)),
                ('q15', models.CharField(max_length=50)),
                ('emotion', models.CharField(max_length=50)),
                ('happiness_index', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
