# Generated by Django 4.1.5 on 2023-04-04 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_student_feedback_form_student_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_feedback',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='student_feedback',
            name='student_roll_no',
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_no', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
