# Generated by Django 4.1.5 on 2023-04-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_feedback_standard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_feedback',
            name='emotion',
        ),
    ]
