# Generated by Django 4.1.5 on 2023-04-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_feedback_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='username',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
