# Generated by Django 4.1.5 on 2023-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='feedback_pred',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_feedback',
            name='qus_pred',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_feedback',
            name='feedback',
            field=models.CharField(max_length=500),
        ),
    ]
