# Generated by Django 5.0.1 on 2024-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_feedback_feedback_pred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='standard',
            field=models.CharField(max_length=60),
        ),
    ]
