# Generated by Django 4.2.7 on 2024-04-16 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_student_profile_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('designation', models.CharField(max_length=70)),
                ('q1', models.CharField(max_length=50)),
                ('q2', models.CharField(max_length=50)),
                ('q3', models.CharField(max_length=50)),
                ('q4', models.CharField(max_length=50)),
                ('q5', models.CharField(max_length=50)),
                ('q6', models.CharField(max_length=50)),
                ('q7', models.CharField(max_length=50)),
                ('q8', models.CharField(max_length=50)),
                ('q9', models.CharField(max_length=50)),
                ('q10', models.CharField(max_length=50)),
                ('q11', models.CharField(max_length=50)),
                ('q12', models.CharField(max_length=50)),
                ('q13', models.CharField(max_length=50)),
                ('q14', models.CharField(max_length=50)),
                ('q15', models.CharField(max_length=50)),
                ('qus_pred', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=500)),
                ('feedback_pred', models.CharField(max_length=50)),
                ('happiness_index', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='profile_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='student_feedback',
        ),
        migrations.DeleteModel(
            name='student_profile',
        ),
    ]
